name: Secure Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Secure Step
        run: echo "Deploying securely"

        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
